export const FETCH_COMICS_SAGA = 'FETCH_COMICS_SAGA';
export const FETCH_COMICS_START = 'FETCH_COMICS_START';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';
export const FETCH_COMICS_FAIL = 'FETCH_COMICS_FAIL';

export const FETCH_COMIC_DETAILS_SAGA = 'FETCH_COMIC_DETAILS_SAGA';
export const FETCH_COMIC_DETAILS_START = 'FETCH_COMIC_DETAILS_START';
export const FETCH_COMIC_DETAILS_SUCCESS = 'FETCH_COMIC_DETAILS_SUCCESS';
export const FETCH_COMIC_DETAILS_FAIL = 'FETCH_COMIC_DETAILS_FAIL';

export const SET_SEARCH_RESULT_OFFSET = 'SET_SEARCH_RESULT_OFFSET';